# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "datatools-address-autofill"
handle = "datatools-address-autofill"
application_url = "https://pull-occur-failures-winter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dicho-checkout-ext.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pull-occur-failures-winter.trycloudflare.com/auth/callback",
  "https://pull-occur-failures-winter.trycloudflare.com/auth/shopify/callback",
  "https://pull-occur-failures-winter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
